### ISSUE TITLE
Use morph_hw with vesc 75/300

### ISSUE THREAD

**Issue by saeedarabi92** [roaldlemmens/morph_hw#6]
Hi,

I need more HP for my application. The hoverboard hub motors are not powerful enough for my application. I am thinking to use  [vesc 75/300](https://trampaboards.com/single-vesc-75v-300a-in-cnc-t6-silicone-sealed-aluminum-box--the-most-powerful-vedder-electronic-speed-controller-ever-p-26284.html) and more powerful hub motor. 
Would it be possible to use this speed controller? And which part of the code should I modify? 

Any hint is appreciated. Thank you in advance.

**Comment by roaldlemmens** [comment]
I only have experience using VESC 4.12 hardware. I see you already posted this question on the vesc driver repo, which is a better place. So I'll close this one.
